'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------
Namespace S130793

    Public Partial Class _Default

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' Button1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Button1 As Global.System.Web.UI.WebControls.Button

        ''' <summary>
        ''' ASPxPivotGrid1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

        ''' <summary>
        ''' field1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected field1 As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' field control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected field As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        ''' <summary>
        ''' ASPxPivotGridExporter1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGridExporter

        ''' <summary>
        ''' SqlDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
